----CREATE DATABASE `connectdb` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
--CREATE DATABASE `connectdb`;
--
---- connectdb.`user` definition
--
--CREATE TABLE `user` (
--  `id` bigint NOT NULL AUTO_INCREMENT,
--  `email` varchar(255) DEFAULT NULL,
--  `password` varchar(255) DEFAULT NULL,
--  PRIMARY KEY (`id`),
--  UNIQUE KEY `UKob8kqyqqgmefl0aco34akdtpe` (`email`)
--) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;